#### Part A — Load and inspect

In [145]:
import pandas as pd

students = pd.read_csv("data/raw/students_messy.csv", na_values=["", "missing", "N/A", "-"])

original_row_count = len(students)
missing_before = students.isna().sum().copy()
original_columns = students.columns.tolist()
students.head()

,student_id,name,program,city,attendance,assignment,midterm,final,admission_date
0,1001,Ali Khan,BSAI,Islamabad,85.0,78.0,72.0,81.0,2025-09-01
1,1002,Sara Ahmed,BS AI,islamabad,NaN,88.0,68.0,75.0,01/09/2025
2,1003,Ahmed Raza,BSAI,Rawalpindi,92.0,80.0,NaN,88.0,2025/09/01
3,1003,Ahmed Raza,BSAI,Rawalpindi,92.0,80.0,NaN,88.0,2025/09/01
4,1004,Ayesha Noor,BSCS,Rwp,110.0,86.0,75.0,90.0,09-01-2025

In [146]:
# A1. Display head(), tail(), columns, and the row and column counts.
print("First rows:", students.head(), sep="\n")
print("Last rows:", students.tail(), sep="\n")
print("Columns:", students.columns.tolist())
print("Rows:", students.shape[0], "Columns:", students.shape[1])

First rows:
   student_id         name program        city  attendance  assignment  \
0        1001     Ali Khan    BSAI   Islamabad        85.0        78.0
1        1002   Sara Ahmed   BS AI   islamabad         NaN        88.0
2        1003   Ahmed Raza    BSAI  Rawalpindi        92.0        80.0
3        1003   Ahmed Raza    BSAI  Rawalpindi        92.0        80.0
4        1004  Ayesha Noor    BSCS         Rwp       110.0        86.0

   midterm  final admission_date
0     72.0   81.0     2025-09-01
1     68.0   75.0     01/09/2025
2      NaN   88.0     2025/09/01
3      NaN   88.0     2025/09/01
4     75.0   90.0     09-01-2025
Last rows:
    student_id          name program        city  attendance  assignment  \
6         1006  Zainab Malik    BSDS  RAWALPINDI        81.0        91.0
7         1007   Usman Tariq      AI   Islamabad        69.0        60.0
8         1008  Maryam Iqbal    BSAI         NaN        88.0        89.0
9         1009   Bilal Ahmed    BSCS   Islamabad        -5.0        55.0
10        1010     Hira Khan   BS DS  Rawalpindi        79.0         NaN

    midterm  final    admission_date
6      84.0   93.0        2025-09-02
7      48.0   55.0  September 3 2025
8      87.0   94.0        2025-09-03
9      42.0   49.0        2025-09-04
10     72.0   80.0        2025-09-04
Columns: ['student_id', 'name', 'program', 'city', 'attendance', 'assignment', 'midterm', 'final', 'admission_date']
Rows: 11 Columns: 9

In [147]:
# A2. Display info() and describe(include="all").
students.info()
students.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      11 non-null     int64
 1   name            11 non-null     object
 2   program         11 non-null     object
 3   city            10 non-null     object
 4   attendance      10 non-null     float64
 5   assignment      10 non-null     float64
 6   midterm         9 non-null      float64
 7   final           10 non-null     float64
 8   admission_date  11 non-null     object
dtypes: float64(4), int64(1), object(4)
memory usage: 920.0+ bytes

,student_id,name,program,city,attendance,assignment,midterm,final,admission_date
count,11.000000,11,11,10,10.000000,10.000000,9.000000,10.000000,11
unique,NaN,10,7,5,NaN,NaN,NaN,NaN,8
top,NaN,Ahmed Raza,BSAI,Islamabad,NaN,NaN,NaN,NaN,2025-09-01
freq,NaN,2,4,4,NaN,NaN,NaN,NaN,2
mean,1005.272727,NaN,NaN,NaN,76.500000,77.700000,66.666667,79.300000,NaN
std,2.969542,NaN,NaN,NaN,30.801335,12.374256,15.866632,15.635075,NaN
min,1001.000000,NaN,NaN,NaN,-5.000000,55.000000,42.000000,49.000000,NaN
25%,1003.000000,NaN,NaN,NaN,75.250000,72.000000,52.000000,76.250000,NaN
50%,1005.000000,NaN,NaN,NaN,83.000000,80.000000,72.000000,84.500000,NaN
75%,1007.500000,NaN,NaN,NaN,91.000000,87.500000,75.000000,89.500000,NaN
max,1010.000000,NaN,NaN,NaN,110.000000,91.000000,87.000000,94.000000,NaN

In [148]:
# A3. Display missing counts, exact duplicate count, and program and city labels; note data issues.
print("Missing columns:", missing_before[missing_before > 0], sep="\n")
print("Exact duplicates:", students.duplicated().sum())
print("Programs:", students["program"].unique())
print("Cities:", students["city"].unique())
# Supplied data: duplicate ID 1003, attendance 110/-5, missing marks,
# inconsistent program/city labels, and mixed or ambiguous date formats.
# Numeric columns may already be numeric because read_csv recognizes the markers.

Missing columns:
city          1
attendance    1
assignment    1
midterm       2
final         1
dtype: int64
Exact duplicates: 1
Programs: ['BSAI' 'BS AI' 'BSCS' ' BS-AI ' 'BSDS' 'AI' 'BS DS']
Cities: ['Islamabad' 'islamabad' 'Rawalpindi' 'Rwp' 'RAWALPINDI' nan]

#### Part B — Select, filter, and handle duplicates

In [149]:
# B1.1. Display the six-column performance view for the main performance columns.
performance = students.loc[:, [
    "student_id", "program", "attendance", "assignment", "midterm", "final"
]]
performance

    student_id  program  attendance  assignment  midterm  final
0         1001     BSAI        85.0        78.0     72.0   81.0
1         1002    BS AI         NaN        88.0     68.0   75.0
2         1003     BSAI        92.0        80.0      NaN   88.0
3         1003     BSAI        92.0        80.0      NaN   88.0
4         1004     BSCS       110.0        86.0     75.0   90.0
5         1005   BS-AI         74.0        70.0     52.0    NaN
6         1006     BSDS        81.0        91.0     84.0   93.0
7         1007       AI        69.0        60.0     48.0   55.0
8         1008     BSAI        88.0        89.0     87.0   94.0
9         1009     BSCS        -5.0        55.0     42.0   49.0
10        1010    BS DS        79.0         NaN     72.0   80.0

In [150]:
# B1.2. Select likely AI students using str.contains() and display their IDs, names, and programs.
possible_ai = students.loc[
    students["program"].astype("string").str.contains("AI", case=False, na=False)
]
possible_ai[["student_id", "name", "program"]]

   student_id          name  program
0        1001      Ali Khan     BSAI
1        1002    Sara Ahmed    BS AI
2        1003    Ahmed Raza     BSAI
3        1003    Ahmed Raza     BSAI
5        1005     Hamza Ali   BS-AI
7        1007   Usman Tariq       AI
8        1008  Maryam Iqbal     BSAI

In [151]:
# B1.3. Display students below 75% attendance.
low_attendance = students.loc[students["attendance"] < 75]
low_attendance[["student_id", "name", "attendance"]]

   student_id         name  attendance
5        1005    Hamza Ali        74.0
7        1007  Usman Tariq        69.0
9        1009  Bilal Ahmed        -5.0

In [152]:
# B1.4. Display students with final marks at least 80.
high_final = students.loc[students["final"] >= 80]
high_final[["student_id", "name", "final"]]

    student_id          name  final
0         1001      Ali Khan   81.0
2         1003    Ahmed Raza   88.0
3         1003    Ahmed Raza   88.0
4         1004   Ayesha Noor   90.0
6         1006  Zainab Malik   93.0
8         1008  Maryam Iqbal   94.0
10        1010     Hira Khan   80.0

In [153]:
# B1.5. Sort performance by final descending with missing values last; note remaining data issues.
performance_sorted = performance.sort_values(by="final", ascending=False, na_position="last")
# Filtering does not clean data: duplicate 1003 and attendance 110/-5 remain.
performance_sorted

    student_id  program  attendance  assignment  midterm  final
8         1008     BSAI        88.0        89.0     87.0   94.0
6         1006     BSDS        81.0        91.0     84.0   93.0
4         1004     BSCS       110.0        86.0     75.0   90.0
3         1003     BSAI        92.0        80.0      NaN   88.0
2         1003     BSAI        92.0        80.0      NaN   88.0
0         1001     BSAI        85.0        78.0     72.0   81.0
10        1010    BS DS        79.0         NaN     72.0   80.0
1         1002    BS AI         NaN        88.0     68.0   75.0
7         1007       AI        69.0        60.0     48.0   55.0
9         1009     BSCS        -5.0        55.0     42.0   49.0
5         1005   BS-AI         74.0        70.0     52.0    NaN

##### B2. Investigate duplicates

In [154]:
# B2 — INVESTIGATE DUPLICATES

# B2.1. Display all exact duplicate occurrences and count rows to remove.
# keep=False marks both the original and its duplicate.

duplicate_rows = students.loc[students.duplicated(keep=False)].copy()
duplicates_removed = int(students.duplicated().sum())
print("Rows to remove:", duplicates_removed)
duplicate_rows

Rows to remove: 1

,student_id,name,program,city,attendance,assignment,midterm,final,admission_date
2,1003,Ahmed Raza,BSAI,Rawalpindi,92.0,80.0,NaN,88.0,2025/09/01
3,1003,Ahmed Raza,BSAI,Rawalpindi,92.0,80.0,NaN,88.0,2025/09/01

In [155]:
# B2.2. Remove exact duplicates and reset the index without adding an old-index column.
cleaning_log = []

students = students.drop_duplicates().reset_index(drop=True)
cleaning_log.append({"student_id": "1003", "column": "whole row",
    "original_value": "exact duplicate", "decision": "Keep first occurrence",
    "reason": "All column values match; one redundant row removed"})
students

,student_id,name,program,city,attendance,assignment,midterm,final,admission_date
0,1001,Ali Khan,BSAI,Islamabad,85.0,78.0,72.0,81.0,2025-09-01
1,1002,Sara Ahmed,BS AI,islamabad,NaN,88.0,68.0,75.0,01/09/2025
2,1003,Ahmed Raza,BSAI,Rawalpindi,92.0,80.0,NaN,88.0,2025/09/01
3,1004,Ayesha Noor,BSCS,Rwp,110.0,86.0,75.0,90.0,09-01-2025
4,1005,Hamza Ali,BS-AI,Islamabad,74.0,70.0,52.0,NaN,2025-09-01
5,1006,Zainab Malik,BSDS,RAWALPINDI,81.0,91.0,84.0,93.0,2025-09-02
6,1007,Usman Tariq,AI,Islamabad,69.0,60.0,48.0,55.0,September 3 2025
7,1008,Maryam Iqbal,BSAI,NaN,88.0,89.0,87.0,94.0,2025-09-03
8,1009,Bilal Ahmed,BSCS,Islamabad,-5.0,55.0,42.0,49.0,2025-09-04
9,1010,Hira Khan,BS DS,Rawalpindi,79.0,NaN,72.0,80.0,2025-09-04

In [156]:
# B2.3. Check repeated student IDs and explain why non-identical records need investigation.
repeated_ids = students.loc[students.duplicated("student_id", keep=False)]
print("Repeated ID occurrences:", students.duplicated("student_id").sum())
# Different records with the same ID may represent updates or separate periods.
# Do not drop them until the source and a valid selection rule are verified.
repeated_ids

Repeated ID occurrences: 0

Empty DataFrame
Columns: [student_id, name, program, city, attendance, assignment, midterm, final, admission_date]
Index: []

##### B3 — STANDARDIZE TEXT

In [157]:
# B3 — STANDARDIZE TEXT

# B3.1. Convert program and city to Pandas string types and remove leading and trailing spaces.

students["program"] = (students["program"].astype("string").str.strip())

students["city"] = (students["city"].astype("string").str.strip())

students[["program", "city"]]

  program        city
0    BSAI   Islamabad
1   BS AI   islamabad
2    BSAI  Rawalpindi
3    BSCS         Rwp
4   BS-AI   Islamabad
5    BSDS  RAWALPINDI
6      AI   Islamabad
7    BSAI        <NA>
8    BSCS   Islamabad
9   BS DS  Rawalpindi

In [158]:
# B3.2. Uppercase programs and map equivalent labels to BSAI or BSDS.
program_mapping = {"BS AI": "BSAI", "BS-AI": "BSAI", "AI": "BSAI", "BS DS": "BSDS"}
students["program"] = students["program"].str.upper().replace(program_mapping)
students["program"].unique()

<StringArray>
['BSAI', 'BSCS', 'BSDS']
Length: 3, dtype: string

In [159]:
# B3.3. Title-case cities, replace Rwp with Rawalpindi, fill missing cities with Unknown, and verify labels.
students["city"] = (students["city"].str.title().replace({"Rwp": "Rawalpindi"}).fillna("Unknown"))

print("Cities:", students["city"].unique())

Cities: <StringArray>
['Islamabad', 'Rawalpindi', 'Unknown']
Length: 3, dtype: string

#### Part C — Types, ranges, and missing values (35 minutes)

##### C1. Convert types

In [160]:
assessment_columns = ["attendance", "assignment", "midterm", "final"]
students[assessment_columns].dtypes

attendance    float64
assignment    float64
midterm       float64
final         float64
dtype: object

In [161]:
# C1.1. Convert attendance, assignment, midterm, and final to numeric with errors="coerce".
assessment_columns = ["attendance", "assignment", "midterm", "final"]
conversion_columns = assessment_columns + ["admission_date"]
missing_before_conversion = students[conversion_columns].isna().sum().copy()
original_dates = students["admission_date"].copy()
for column in assessment_columns:
    students[column] = pd.to_numeric(students[column], errors="coerce")
students[assessment_columns].dtypes

attendance    float64
assignment    float64
midterm       float64
final         float64
dtype: object

In [162]:
students["admission_date"]

0          2025-09-01
1          01/09/2025
2          2025/09/01
3          09-01-2025
4          2025-09-01
5          2025-09-02
6    September 3 2025
7          2025-09-03
8          2025-09-04
9          2025-09-04
Name: admission_date, dtype: object

In [163]:
   # C1.2. Parse mixed admission dates with dayfirst=True and errors="coerce".
   # ISO-style dates (2025-09-01, 2025/09/01) year-first hain, unko dayfirst se nahi parse karna.
   s = students["admission_date"].astype("string")
   year_first = s.str.match(r"^\d{4}[-/]")

   parsed_iso = pd.to_datetime(s.where(year_first), format="mixed", errors="coerce")
   parsed_dayfirst = pd.to_datetime(s.where(~year_first), format="mixed", dayfirst=True, errors="coerce")

   students["admission_date"] = parsed_iso.fillna(parsed_dayfirst)
   students["admission_date"]

0   2025-09-01
1   2025-09-01
2   2025-09-01
3   2025-01-09
4   2025-09-01
5   2025-09-02
6   2025-09-03
7   2025-09-03
8   2025-09-04
9   2025-09-04
Name: admission_date, dtype: datetime64[ns]

In [164]:
# C1.3. Convert student_id to string and display dtypes and newly introduced missing counts.
students["student_id"] = students["student_id"].astype("string")
new_missing = students[conversion_columns].isna().sum() - missing_before_conversion
print(students.dtypes)
print("New missing values:", new_missing, sep="\n")

student_id        string[python]
name                      object
program           string[python]
city              string[python]
attendance               float64
assignment               float64
midterm                  float64
final                    float64
admission_date    datetime64[ns]
dtype: object
New missing values:
attendance        0
assignment        0
midterm           0
final             0
admission_date    0
dtype: int64

##### C2. Validate ranges

In [165]:
# C2.1. Identify values outside 0–100 and store affected records for review.
invalid_mask = (students[assessment_columns] < 0) | (students[assessment_columns] > 100)
invalid_records = students.loc[invalid_mask.any(axis=1)].copy()
invalid_records

,student_id,name,program,city,attendance,assignment,midterm,final,admission_date
3,1004,Ayesha Noor,BSCS,Rawalpindi,110.0,86.0,75.0,90.0,2025-01-09
8,1009,Bilal Ahmed,BSCS,Islamabad,-5.0,55.0,42.0,49.0,2025-09-04

In [166]:
# C2.2. Record each invalid value, the cleaning decision, and the reason in cleaning_log.
for column in assessment_columns:
    for _, row in students.loc[invalid_mask[column]].iterrows():
        cleaning_log.append({
            "student_id": row["student_id"], "column": column,
            "original_value": row[column], "decision": "Replace with missing value",
            "reason": "Outside the valid range 0–100"
        })
pd.DataFrame(cleaning_log)

,student_id,column,original_value,decision,reason
0,1003,whole row,exact duplicate,Keep first occurrence,All column values match; one redundant row rem...
1,1004,attendance,110.0,Replace with missing value,Outside the valid range 0–100
2,1009,attendance,-5.0,Replace with missing value,Outside the valid range 0–100

In [167]:
# C2.3. Replace invalid values with pd.NA using .loc and verify no out-of-range values remain.
for column in assessment_columns:
    students.loc[invalid_mask[column], column] = pd.NA

remaining_invalid = (students[assessment_columns] < 0) | (students[assessment_columns] > 100)
assert not remaining_invalid.any().any()
print("Remaining invalid values:", int(remaining_invalid.sum().sum()))

Remaining invalid values: 0

##### C3. Handle missing values

In [168]:
# C3.1. Record missing counts and affected IDs before imputation; retain flags for imputed values.
missing_before_imputation = students[original_columns].isna().sum().copy()
affected_ids = {}
for column in assessment_columns:
    affected_ids[column] = students.loc[students[column].isna(), "student_id"].tolist()
    students[f"{column}_imputed"] = students[column].isna()
print("Affected IDs:", affected_ids)
missing_before_imputation

Affected IDs: {'attendance': ['1002', '1004', '1009'], 'assignment': ['1010'], 'midterm': ['1003'], 'final': ['1005']}

student_id        0
name              0
program           0
city              0
attendance        3
assignment        1
midterm           1
final             1
admission_date    0
dtype: int64

In [169]:
# C3.2. Fill attendance with its program median, then use the original overall median as fallback.
overall_median = students["attendance"].median()
program_median = students.groupby("program")["attendance"].transform("median")
attendance_fill = program_median.fillna(overall_median)

for index in students.index[students["attendance_imputed"]]:
    cleaning_log.append({
        "student_id": students.loc[index, "student_id"], "column": "attendance",
        "original_value": "missing", "decision": f"Fill with {attendance_fill.loc[index]}",
        "reason": "Program median; original overall median if group has no valid values"
    })

students["attendance"] = students["attendance"].fillna(attendance_fill)
students[["student_id", "program", "attendance", "attendance_imputed"]]

  student_id program  attendance  attendance_imputed
0       1001    BSAI        85.0               False
1       1002    BSAI        85.0                True
2       1003    BSAI        92.0               False
3       1004    BSCS        81.0                True
4       1005    BSAI        74.0               False
5       1006    BSDS        81.0               False
6       1007    BSAI        69.0               False
7       1008    BSAI        88.0               False
8       1009    BSCS        81.0                True
9       1010    BSDS        79.0               False

In [170]:
# C3.3. Fill missing assessment marks with column medians and log the rule.
for column in ["assignment", "midterm", "final"]:
    median_value = students[column].median()
    for student_id in affected_ids[column]:
        cleaning_log.append({
            "student_id": student_id, "column": column, "original_value": "missing",
            "decision": f"Fill with column median {median_value}",
            "reason": "Classroom simulation only; retained imputation flag"
        })
    students[column] = students[column].fillna(median_value)

students[["student_id", "assignment", "midterm", "final",
          "assignment_imputed", "midterm_imputed", "final_imputed"]]

,student_id,assignment,midterm,final,assignment_imputed,midterm_imputed,final_imputed
0,1001,78.0,72.0,81.0,False,False,False
1,1002,88.0,68.0,75.0,False,False,False
2,1003,80.0,72.0,88.0,False,True,False
3,1004,86.0,75.0,90.0,False,False,False
4,1005,70.0,52.0,81.0,False,False,True
5,1006,91.0,84.0,93.0,False,False,False
6,1007,60.0,48.0,55.0,False,False,False
7,1008,89.0,87.0,94.0,False,False,False
8,1009,55.0,42.0,49.0,False,False,False
9,1010,80.0,72.0,80.0,True,False,False

In [171]:
# C3.4. Store missing_after, compare counts, and verify scoring columns have no missing values; state limitations.
missing_after = students[original_columns].isna().sum()
assert students[assessment_columns].notna().all().all()

pd.DataFrame({"Before imputation": missing_before_imputation, "After": missing_after})

                Before imputation  After
student_id                      0      0
name                            0      0
program                         0      0
city                            0      0
attendance                      3      0
assignment                      1      0
midterm                         1      0
final                           1      0
admission_date                  0      0

In [182]:
att = pd.read_csv("data/raw/attendance.csv", dtype={"student_id": "string"})
rows_before = len(students)
students = students.merge(att, on="student_id", how="left", validate="one_to_one")
assert len(students) == rows_before
print("Rows before/after merge:", rows_before, len(students))

Rows before/after merge: 10 10

#### Part D — Create features and summarize

##### D1. Create features

In [172]:
# D1.1. Calculate weighted_score using assignment 20%, midterm 30%, and final 50% for this exercise.
students["weighted_score"] = (
    students["assignment"] * 0.20 + students["midterm"] * 0.30 + students["final"] * 0.50
)
# These are exercise weights, not the official course assessment policy.
students[["student_id", "weighted_score"]]

  student_id  weighted_score
0       1001            77.7
1       1002            75.5
2       1003            81.6
3       1004            84.7
4       1005            70.1
5       1006            89.9
6       1007            53.9
7       1008            90.9
8       1009            48.1
9       1010            77.6

In [173]:
# D1.2. Create attendance_status: Low below 75, Satisfactory from 75 to below 85, Excellent from 85.
import numpy as np

students["attendance_status"] = np.select(
    [students["attendance"] >= 85, students["attendance"] >= 75],
    ["Excellent", "Satisfactory"], default="Low"
)
students[["student_id", "attendance", "attendance_status"]]

  student_id  attendance attendance_status
0       1001        85.0         Excellent
1       1002        85.0         Excellent
2       1003        92.0         Excellent
3       1004        81.0      Satisfactory
4       1005        74.0               Low
5       1006        81.0      Satisfactory
6       1007        69.0               Low
7       1008        88.0         Excellent
8       1009        81.0      Satisfactory
9       1010        79.0      Satisfactory

In [174]:
# D1.3. Create grades A >= 85, B >= 75, C >= 65, D >= 50, otherwise F, using np.select().
conditions = [students["weighted_score"] >= 85,
              students["weighted_score"] >= 75,
              students["weighted_score"] >= 65,
              students["weighted_score"] >= 50]
students["grade"] = np.select(conditions, ["A", "B", "C", "D"], default="F")
students[["student_id", "weighted_score", "grade"]]

  student_id  weighted_score grade
0       1001            77.7     B
1       1002            75.5     B
2       1003            81.6     B
3       1004            84.7     B
4       1005            70.1     C
5       1006            89.9     A
6       1007            53.9     D
7       1008            90.9     A
8       1009            48.1     F
9       1010            77.6     B

In [175]:
# D1.4. Flag at_risk when attendance < 75 or weighted_score < 50; display features and verify score bounds.
students["at_risk"] = (students["attendance"] < 75) | (students["weighted_score"] < 50)
assert students["weighted_score"].between(0, 100).all()
students[["student_id", "weighted_score", "attendance_status", "grade", "at_risk"]]

  student_id  weighted_score attendance_status grade  at_risk
0       1001            77.7         Excellent     B    False
1       1002            75.5         Excellent     B    False
2       1003            81.6         Excellent     B    False
3       1004            84.7      Satisfactory     B    False
4       1005            70.1               Low     C     True
5       1006            89.9      Satisfactory     A    False
6       1007            53.9               Low     D     True
7       1008            90.9         Excellent     A    False
8       1009            48.1      Satisfactory     F     True
9       1010            77.6      Satisfactory     B    False

##### D2. Group and summarize

In [176]:
# D2.1. Create program_summary with student count and average weighted score for each program.
program_summary = students.groupby("program").agg(
    student_count=("student_id", "count"), average_score=("weighted_score", "mean")
).reset_index()
program_summary

  program  student_count  average_score
0    BSAI              6          74.95
1    BSCS              2          66.40
2    BSDS              2          83.75

In [177]:
# D2.2. Create and display grade_distribution, then verify both summary counts equal the student count.
grade_distribution = (students["grade"].value_counts().sort_index()
    .rename_axis("grade").reset_index(name="count"))
assert program_summary["student_count"].sum() == len(students)
assert grade_distribution["count"].sum() == len(students)
grade_distribution

  grade  count
0     A      2
1     B      5
2     C      1
3     D      1
4     F      1

#### Part E — Save, report, and commit

##### E1. Complete the lab

In [178]:
# E1.1. Verify IDs are unique and non-missing and all attendance and assessment values are within 0–100.
assert students["student_id"].notna().all()
assert students["student_id"].is_unique
assert students[assessment_columns].notna().all().all()
assert students[assessment_columns].ge(0).all().all()
assert students[assessment_columns].le(100).all().all()
print("All final checks passed.")

All final checks passed.

In [179]:
# E1.2. Save the cleaned data, two summaries, invalid records, and cleaning log; reload and check the cleaned CSV.
from pathlib import Path

# Make sure the output folders exist.
Path("data/processed").mkdir(parents=True, exist_ok=True)
Path("reports").mkdir(parents=True, exist_ok=True)

# Save the cleaned data and summaries.
students.to_csv("data/processed/students_clean.csv", index=False)
program_summary.to_csv("data/processed/program_summary.csv", index=False)
grade_distribution.to_csv("data/processed/grade_distribution.csv", index=False)

# Save records for review and the cleaning log.
invalid_records.to_csv("reports/invalid_records.csv", index=False)
pd.DataFrame(cleaning_log).to_csv("reports/cleaning_log.csv", index=False)

# Reload and verify the cleaned file.
reloaded = pd.read_csv("data/processed/students_clean.csv",
    dtype={"student_id": "string"}
)

assert reloaded.shape == students.shape
assert reloaded["student_id"].tolist() == students["student_id"].tolist()

print("Saved five CSV files; cleaned CSV reloaded successfully.")

Saved five CSV files; cleaned CSV reloaded successfully.

Rows before/after merge: 10 10